### ISSUE TITLE
No syntax highlighting unless 'hls_cache' deleted.

### ISSUE THREAD

**Issue by ghost** [psemiletov/tea-qt#16]
There is no syntax highlighting unless I manually delete '~/.config/tea/hls_cache'.
Ps. Thanks for this awesome program, neat work.
Ps2. I'm on Arch Linux, installed 'TEA' from the Pacman repositories.

**Comment by psemiletov** [comment]
1. Was it the first run of TEA?
2. Did you make and use some custom hightlighting modules?

**Comment by soocki** [comment]
ad1) Nope
ad2) For some reason there was no templates in `./config/tea/hls/` so I copied all from the 'hls' folder
It works, but between program restarts the '~/.config/tea/hls_cache' need to be removed.

**Comment by psemiletov** [comment]
hls folder in source contains modules those built into TEA binary. If you copy them to ./config/tea/hls/, there is a conflict between inner and outer modules.

**Comment by soocki** [comment]
I have them removed, the same behaviour persists, if I don't remove the 'hls_cache' no highlighting at all. Works fine only once, between the program restarts it needs to be removed to work.

**Comment by soocki** [comment]
If you can't beat them join them;
```
#!/bin/bash
rm ~/.config/tea/hls_cache
tea
```

**Comment by psemiletov** [comment]
The hls_cache.txt attached is definitely broken. It's all very strange because if I run TEA on clean install (no  /.config/tea/ at all) all works fine, and hls_cache created and looks like:
asm=:/hls/nasm.xml
ts=:/hls/xml.xml
et cetera.
I think I need to install Arch Linux and inspect such strange TEA behavior on that distro :)
And what if you delete the  /.config/tea/hls directory?

**Comment by soocki** [comment]
I have deleted the '~/.config/tea/hls' dir and after that the whole `~/.config/tea` but no go. I tried compiling from source as opposed to the version in pacman repositories, both acting the same. Very strange indeed man.

**Comment by psemiletov** [comment]
Can you try to compile and run the current github version? I think I've fixed that stuff, but I'm not sure.

**Comment by soocki** [comment]
Unfortunately whatever you did didn't fix it, the only change is that the trick with deleting 'hls-cache' does not work any more, which is worse than before. Sorry man.

**Comment by psemiletov** [comment]
All hls-cache stuff has been removed, now TEA updated syntax hl modules without the caching. Please try if it work for you.
